name: Maven Package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Get version
      run: echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV

    - name: Build
      run: docker build . --tag builder

    - name: Run
      run: docker run -v ${{ github.workspace }}:/code:Z builder

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -s ${{ github.workspace}}/settings.xml -f rpm.pom.xml -B -Drevision=${{ env.RELEASE_VERSION }} -Dsha1= -Dchangelist= deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
